repos:
  # Check various file formats.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
        exclude: \.json$
        files: \.py$
      - id: trailing-whitespace
      - id: mixed-line-ending

  # For linting & style checks.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        name: format code with ruff

  # To make sure we don't commit anything incorrectly.
  - repo: local
    hooks:
      - id: do-not-commit-openapi-key
        name: check for open api keys
        entry: OPENAI_API_KEY=[a-zA-Z0-9_-]
        language: pygrep
        types: [text]
      - id: do-not-commit-local-dev
        name: check for local dev environment
        entry: ^rosetta = \{ path =
        language: pygrep
        types: [toml]

  # For making sure the poetry.lock file is up-to-date.
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
    - id: poetry-check
    - id: poetry-lock